[2024-10-05T20:21:50.085+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T20:21:50.095+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T13:21:46.276882+00:00 [queued]>
[2024-10-05T20:21:50.101+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T13:21:46.276882+00:00 [queued]>
[2024-10-05T20:21:50.101+0700] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-05T20:21:50.115+0700] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_talend_job> on 2024-10-05 13:21:46.276882+00:00
[2024-10-05T20:21:50.121+0700] {standard_task_runner.py:72} INFO - Started process 252545 to run task
[2024-10-05T20:21:50.127+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'talend_job_dag_Sync_Mysql_to_DWh_job', 'run_talend_job', 'manual__2024-10-05T13:21:46.276882+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/Sync_Mysql_to_DWh_job.py', '--cfg-path', '/tmp/tmpwhhkwxp_']
[2024-10-05T20:21:50.128+0700] {standard_task_runner.py:105} INFO - Job 29: Subtask run_talend_job
[2024-10-05T20:21:50.173+0700] {task_command.py:467} INFO - Running <TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.run_talend_job manual__2024-10-05T13:21:46.276882+00:00 [running]> on host linux-ip-147
[2024-10-05T20:21:50.219+0700] {abstractoperator.py:778} ERROR - Exception rendering Jinja template for task 'run_talend_job', field 'bash_command'. Template: 'sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/usr/local/lib/python3.10/dist-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh
[2024-10-05T20:21:50.221+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3114, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3533, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 1419, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/usr/local/lib/python3.10/dist-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh
[2024-10-05T20:21:50.229+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-05T20:21:50.229+0700] {logging_mixin.py:190} INFO - Task start:2024-10-05 13:21:50.095365+00:00 end:2024-10-05 13:21:50.228655+00:00 duration:0.13329
[2024-10-05T20:21:50.229+0700] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_talend_job> dag:<DAG: talend_job_dag_Sync_Mysql_to_DWh_job> dagrun:<DagRun talend_job_dag_Sync_Mysql_to_DWh_job @ 2024-10-05 13:21:46.276882+00:00: manual__2024-10-05T13:21:46.276882+00:00, state:running, queued_at: 2024-10-05 13:21:46.310232+00:00. externally triggered: True>
[2024-10-05T20:21:50.230+0700] {logging_mixin.py:190} INFO - Failure caused by sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh
[2024-10-05T20:21:50.230+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=talend_job_dag_Sync_Mysql_to_DWh_job, task_id=run_talend_job, run_id=manual__2024-10-05T13:21:46.276882+00:00, execution_date=20241005T132146, start_date=20241005T132150, end_date=20241005T132150
[2024-10-05T20:21:50.245+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T20:21:50.246+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task run_talend_job (sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh; 252545)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3114, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3533, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 1419, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/usr/local/lib/python3.10/dist-packages/airflow/template/templater.py", line 168, in render_template
    template = jinja_env.get_template(value)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh /opt/Sync_Mysql_to_DWH_Job/run_Sync_Mysql_to_DWH_job.sh
[2024-10-05T20:21:50.268+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T20:21:50.308+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T20:21:50.309+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
