[2024-10-05T21:35:37.578+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T21:35:37.587+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.notify_success manual__2024-10-05T14:30:18.597436+00:00 [queued]>
[2024-10-05T21:35:37.594+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.notify_success manual__2024-10-05T14:30:18.597436+00:00 [queued]>
[2024-10-05T21:35:37.594+0700] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-05T21:35:37.608+0700] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): notify_success> on 2024-10-05 14:30:18.597436+00:00
[2024-10-05T21:35:37.612+0700] {standard_task_runner.py:72} INFO - Started process 256820 to run task
[2024-10-05T21:35:37.626+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'talend_job_dag_Sync_Mysql_to_DWh_job', 'notify_success', 'manual__2024-10-05T14:30:18.597436+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/Sync_Mysql_to_DWh_job.py', '--cfg-path', '/tmp/tmpt2ogca8h']
[2024-10-05T21:35:37.628+0700] {standard_task_runner.py:105} INFO - Job 49: Subtask notify_success
[2024-10-05T21:35:37.692+0700] {task_command.py:467} INFO - Running <TaskInstance: talend_job_dag_Sync_Mysql_to_DWh_job.notify_success manual__2024-10-05T14:30:18.597436+00:00 [running]> on host linux-ip-147
[2024-10-05T21:35:37.773+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='talend_job_dag_Sync_Mysql_to_DWh_job' AIRFLOW_CTX_TASK_ID='notify_success' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T14:30:18.597436+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T14:30:18.597436+00:00'
[2024-10-05T21:35:37.775+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-05T21:35:37.775+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-05T21:35:37.776+0700] {logging_mixin.py:190} INFO - Current task name:notify_success state:running start_date:2024-10-05 14:35:37.588186+00:00
[2024-10-05T21:35:37.776+0700] {logging_mixin.py:190} INFO - Dag name:talend_job_dag_Sync_Mysql_to_DWh_job and current dag run status:running
[2024-10-05T21:35:37.776+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T21:35:37.778+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: notify_success_callback() missing 1 required positional argument: 'context'
[2024-10-05T21:35:37.784+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-05T21:35:37.784+0700] {logging_mixin.py:190} INFO - Task start:2024-10-05 14:35:37.588186+00:00 end:2024-10-05 14:35:37.783706+00:00 duration:0.19552
[2024-10-05T21:35:37.785+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): notify_success> dag:<DAG: talend_job_dag_Sync_Mysql_to_DWh_job> dagrun:<DagRun talend_job_dag_Sync_Mysql_to_DWh_job @ 2024-10-05 14:30:18.597436+00:00: manual__2024-10-05T14:30:18.597436+00:00, state:running, queued_at: 2024-10-05 14:30:18.635227+00:00. externally triggered: True>
[2024-10-05T21:35:37.785+0700] {logging_mixin.py:190} INFO - Failure caused by notify_success_callback() missing 1 required positional argument: 'context'
[2024-10-05T21:35:37.785+0700] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=talend_job_dag_Sync_Mysql_to_DWh_job, task_id=notify_success, run_id=manual__2024-10-05T14:30:18.597436+00:00, execution_date=20241005T143018, start_date=20241005T143537, end_date=20241005T143537
[2024-10-05T21:35:37.800+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T21:35:37.801+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task notify_success (notify_success_callback() missing 1 required positional argument: 'context'; 256820)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/dist-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: notify_success_callback() missing 1 required positional argument: 'context'
[2024-10-05T21:35:37.834+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T21:35:37.855+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T21:35:37.856+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
